### PR TITLE
Question functionality developed and tested.

### PR DESCRIPTION
**Pull request by iiitb-sambathkumar**
Worked on the below issues, specific to Question functionality and checked-in the code to be merged with master. Please review and merge them

https://github.com/rajaramghosh/quora/issues/6
https://github.com/rajaramghosh/quora/issues/7
https://github.com/rajaramghosh/quora/issues/8
https://github.com/rajaramghosh/quora/issues/9
https://github.com/rajaramghosh/quora/issues/10

### CODE REVIEW

**Review by nandisaikat — COMMENTED** [review]
Hi Sambath,
I might be missing something, but I dont see the check for validating the access token in the business service layer. From the controller, we will need to send the authorization header and that will need to be validated

**Comment by iiitb-sambathkumar** [comment]
I am passing the requestheader from the controller

**Comment by rajaramghosh** [comment]
Hi Sambath,
Can you first pull the changes in your local repo, merge it there and then create the pull request. 

Have you created local branches, or committed to master directly?

**Comment by iiitb-sambathkumar** [comment]
I already applied the changes after picking the changes. Already did twice once one on Friday and then on Saturday morning .

applied the changes with necessary branches in my fork and then loaded to master. 

Please review the pull request and merge them

**Pull request merged**
